<a href="https://colab.research.google.com/github/chiude0702/chat/blob/master/py0801.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files

uploaded = files.upload()

!ls *.* -1

Saving house-prices.csv to house-prices.csv
house-prices.csv

In [12]:
import re
text = "文本最重要的來源無疑是網格。我們要把網路中的文本獲取形成一個文本數據庫。利用一個爬蟲抓取到網路中的信息。爬蟲的策略有廣度爬取和深度爬取。根據用戶的需求，爬蟲可以有主題爬蟲和通用爬蟲之分。"
p_string = text.split("。")
regex = "^文本"
for line in p_string:
  if re.search(regex,line):
    print(line)
regex = "信息$"
for line in p_string:
  if re.search(regex,line):
    print(line)

文本最重要的來源無疑是網格
利用一個爬蟲抓取到網路中的信息

In [16]:
text_string = ['[重要的]今年第七號颱風23日登陸台灣東部沿海地區','上海發布車庫銷售監管通知：違規者暫停網簽資格','[緊要的]中國對印度發強硬信息，印度急切需要結束對峙']
regex = "^\[[重緊]..]"
for line in text_string:
  if re.search(regex,line):
    print(line)
  else:
    print("no match")

[重要的]今年第七號颱風23日登陸台灣東部沿海地區
no match
[緊要的]中國對印度發強硬信息，印度急切需要結束對峙

In [14]:
import pandas as pd
pd.read_csv("house-prices.csv")

     Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0       1  114300  1790         2          2       2    No         East
1       2  114200  2030         4          2       3    No         East
2       3  114800  1740         3          2       1    No         East
3       4   94700  1980         3          2       3    No         East
4       5  119800  2130         3          3       3    No         East
5       6  114600  1780         3          2       2    No        North
6       7  151600  1830         3          3       3   Yes         West
7       8  150700  2160         4          2       2    No         West
8       9  119200  2110         4          2       3    No         East
9      10  104000  1730         3          3       3    No         East
10     11  132500  2030         3          2       3   Yes         East
11     12  123000  1870         2          2       2   Yes         East
12     13  102600  1910         3          2       4    No        North
13     14  126300  2150         3          3       5   Yes        North
14     15  176800  2590         4          3       4    No         West
15     16  145800  1780         4          2       1    No         West
16     17  147100  2190         3          3       4   Yes         East
17     18   83600  1990         3          3       4    No        North
18     19  111400  1700         2          2       1   Yes         East
19     20  167200  1920         3          3       2   Yes         West
20     21  116200  1790         3          2       3    No         East
21     22  113800  2000         3          2       4    No        North
22     23   91700  1690         3          2       3    No        North
23     24  106100  1820         3          2       3   Yes        North
24     25  156400  2210         4          3       2   Yes         East
25     26  149300  2290         4          3       3    No        North
26     27  137000  2000         4          2       3    No         West
27     28   99300  1700         3          2       2    No         East
28     29   69100  1600         2          2       3    No        North
29     30  188000  2040         4          3       1   Yes         West
..    ...     ...   ...       ...        ...     ...   ...          ...
98     99  145500  2060         3          2       1    No         West
99    100  171000  2080         3          3       2   Yes         West
100   101  103200  2010         3          2       5    No        North
101   102  123100  2260         3          3       5    No         East
102   103  136800  2410         3          3       4    No         East
103   104  211200  2440         4          3       3   Yes         West
104   105   82300  1910         3          2       4    No         East
105   106  146900  2530         4          3       4    No         West
106   107  108500  2130         3          2       4    No        North
107   108  134000  1890         3          2       1   Yes         East
108   109  117000  1990         3          3       3   Yes         East
109   110  108700  2110         3          2       3    No         East
110   111  111600  1710         2          2       1    No        North
111   112  114900  1740         2          2       2    No        North
112   113  123600  1940         2          2       2   Yes         East
113   114  115700  2000         3          2       3   Yes        North
114   115  124500  2010         4          3       2    No         East
115   116  102500  1900         3          3       3    No        North
116   117  199500  2290         5          4       1   Yes         West
117   118  117800  1920         3          2       2    No        North
118   119  150200  1950         3          2       3   Yes        North
119   120  109700  1920         2          2       4    No        North
120   121  110400  1930         2          3       3    No        North
121   122  105600  1930         3          3       3    No         East
122   123  144800  2060         2          2       1   Yes         East
123   124  119700  1900         3          3       3   Yes         East
124   125  147900  2160         4          3       3   Yes         East
125   126  113500  2070         2          2       2    No        North
126   127  149900  2020         3          3       1    No         West
127   128  124600  2250         3          3       4    No        North

[128 rows x 8 columns]